name: auto-merge

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        command: "squash and merge"
        approve: true
        target: minor
